### ISSUE TITLE
generator-cspell-dicts fails to install because of outdated package.json

### ISSUE THREAD

**Issue by d2s** [Jason3S/cspell-dicts#39]
Found various issues with the generator:

- `npm link` failed because `nsp` was not installed on the system.
- Lack of migration from `nsp check` to `npm audit`.
- Outdated Jest version with security issues (found by npm audit).
- Potentially broken test suite that fails to work in a Windows machine.

First issue was caused by the lack of `nsp` command on the system, but when I started to look more closely, found out that [The Node Security Platform service was shut down 30.9.2018](https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting).

[nsp](https://www.npmjs.com/package/nsp) package has a huge big warning banner on the top of page, saying that "This package has been deprecated". It would make sense to replace the `"prepublish": "nsp check"` with the use of [npm audit](https://docs.npmjs.com/cli/audit) command. Documentation for it has the exact details about command options, but similar prepublish command compared to the original nsp could be this:

`"prepublish": "npm audit"`

In addition to that line, we need to remove `nsp` package from the required devDependencies.

When running the `npm link` command again after doing the previous steps, noticed that it found "16 low severity vulnerabilities in 48756 scanned packages" The recommendation was to "run `npm audit fix` to fix 16 of them."

```
                       === npm audit security report ===

# Run  npm install --save-dev jest-cli@23.6.0  to resolve 7 vulnerabilities

  Low             Prototype pollution

  Package         merge

  Dependency of   jest-cli [dev]

  Path            jest-cli > jest-haste-map > sane > exec-sh > merge

  More info       https://nodesecurity.io/advisories/722




  Low             Prototype pollution

  Package         merge

  Dependency of   jest-cli [dev]

  Path            jest-cli > jest-runner > jest-haste-map > sane > exec-sh >
                  merge

  More info       https://nodesecurity.io/advisories/722




  Low             Prototype pollution

  Package         merge

  Dependency of   jest-cli [dev]

  Path            jest-cli > jest-runner > jest-haste-map > sane > watch >
                  exec-sh > merge

  More info       https://nodesecurity.io/advisories/722




  Low             Prototype pollution

  Package         merge

  Dependency of   jest-cli [dev]

  Path            jest-cli > jest-runner > jest-runtime > jest-haste-map >
                  sane > exec-sh > merge

  More info       https://nodesecurity.io/advisories/722




  Low             Prototype pollution

  Package         merge

  Dependency of   jest-cli [dev]

  Path            jest-cli > jest-runner > jest-runtime > jest-haste-map >
                  sane > watch > exec-sh > merge

  More info       https://nodesecurity.io/advisories/722




  Low             Prototype pollution

  Package         merge

  Dependency of   jest-cli [dev]

  Path            jest-cli > jest-runtime > jest-haste-map > sane > exec-sh >
                  merge

  More info       https://nodesecurity.io/advisories/722




  Low             Prototype pollution

  Package         merge

  Dependency of   jest-cli [dev]

  Path            jest-cli > jest-runtime > jest-haste-map > sane > watch >
                  exec-sh > merge

  More info       https://nodesecurity.io/advisories/722



# Run  npm update jest-cli --depth 2  to resolve 6 vulnerabilities

  Low             Prototype pollution

  Package         merge

  Dependency of   jest [dev]

  Path            jest > jest-cli > jest-haste-map > sane > exec-sh > merge

  More info       https://nodesecurity.io/advisories/722




  Low             Prototype pollution

  Package         merge

  Dependency of   jest [dev]

  Path            jest > jest-cli > jest-runner > jest-runtime >
                  jest-haste-map > sane > exec-sh > merge

  More info       https://nodesecurity.io/advisories/722




  Low             Prototype pollution

  Package         merge

  Dependency of   jest [dev]

  Path            jest > jest-cli > jest-haste-map > sane > watch > exec-sh >
                  merge

  More info       https://nodesecurity.io/advisories/722




  Low             Prototype pollution

  Package         merge

  Dependency of   jest [dev]

  Path            jest > jest-cli > jest-runtime > jest-haste-map > sane >
                  exec-sh > merge

  More info       https://nodesecurity.io/advisories/722




  Low             Prototype pollution

  Package         merge

  Dependency of   jest [dev]

  Path            jest > jest-cli > jest-runner > jest-haste-map > sane >
                  watch > exec-sh > merge

  More info       https://nodesecurity.io/advisories/722




  Low             Prototype pollution

  Package         merge

  Dependency of   jest [dev]

  Path            jest > jest-cli > jest-runtime > jest-haste-map > sane >
                  watch > exec-sh > merge

  More info       https://nodesecurity.io/advisories/722



# Run  npm update jest-runner --depth 3  to resolve 2 vulnerabilities

  Low             Prototype pollution

  Package         merge

  Dependency of   jest [dev]

  Path            jest > jest-cli > jest-runner > jest-haste-map > sane >
                  exec-sh > merge

  More info       https://nodesecurity.io/advisories/722




  Low             Prototype pollution

  Package         merge

  Dependency of   jest [dev]

  Path            jest > jest-cli > jest-runner > jest-runtime >
                  jest-haste-map > sane > watch > exec-sh > merge

  More info       https://nodesecurity.io/advisories/722



# Run  npm update merge --depth 6  to resolve 1 vulnerability

  Low             Prototype pollution

  Package         merge

  Dependency of   jest-cli [dev]

  Path            jest-cli > jest-haste-map > sane > watch > exec-sh > merge

  More info       https://nodesecurity.io/advisories/722



found 16 low severity vulnerabilities in 48756 scanned packages
  run `npm audit fix` to fix 16 of them.
```

Before changing anything related to the listed issues, did run `npm test` for running Jest test suite.

Noticed that the test suite would fail to run (on the Windows machine under PowerShell terminal environment).
(Replaced full directory path with ` --- ` on the following terminal log, to clear unrelated details from the output.)

```
> npm test

> generator-cspell-dicts@0.0.0 pretest  --- d2s\cspell-dicts\generator-cspell-dicts
> eslint . --fix

(node:9472) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "xo")

> generator-cspell-dicts@0.0.0 test  --- d2s\cspell-dicts\generator-cspell-dicts
> jest

  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:157
    Unhandled error

  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:158
    Error [ERR_UNHANDLED_ERROR]: Unhandled error. (Error: Did not provide required argument name!)
        at Object.<anonymous>.module.exports.emit (events.js:171:17)
        at _arguments.forEach ( --- \d2s\cspell-dicts\generator-cspell-dicts\node_modules\yeoman-generator\lib\index.js:351:21)
        at Array.forEach (<anonymous>)
        at Object.<anonymous>.module.exports.checkRequiredArgs ( --- d2s\cspell-dicts\generator-cspell-dicts\node_modules\yeoman-generator\lib\index.js:347:21)
        at Object.<anonymous>.module.exports.parseOptions ( --- d2s\cspell-dicts\generator-cspell-dicts\node_modules\yeoman-generator\lib\index.js:332:10)
        at Object.<anonymous>.module.exports.argument ( --- d2s\cspell-dicts\generator-cspell-dicts\node_modules\yeoman-generator\lib\index.js:255:10)
        at new Object.<anonymous>.module.exports ( --- d2s\cspell-dicts\generator-cspell-dicts\generators\app\index.js:14:10)
        at Environment.instantiate ( --- d2s\cspell-dicts\generator-cspell-dicts\node_modules\yeoman-environment\lib\environment.js:407:12)
        at Environment.create ( --- d2s\cspell-dicts\generator-cspell-dicts\node_modules\yeoman-environment\lib\environment.js:385:17)
        at RunContext.Object.<anonymous>.RunContext._run ( --- d2s\cspell-dicts\generator-cspell-dicts\node_modules\yeoman-test\lib\run-context.js:90:29)

 FAIL  __tests__/app.js (26.345s)
  generator-cspell-dicts:app
    × creates files (20ms)

  ● generator-cspell-dicts:app › creates files

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queue_runner.js:41:52)

  ● generator-cspell-dicts:app › creates files

    assert.equal(received, expected) or assert(received)

    Expected value to be equal to:
      true
    Received:
      false

    Message:
      dummyfile.txt, no such file or directory

      11 |
      12 |   it('creates files', () => {
    > 13 |     assert.file([
         |            ^
      14 |       'dummyfile.txt'
      15 |     ]);
      16 |   });

      at convertArgs.forEach.file (node_modules/yeoman-assert/index.js:56:12)
          at Array.forEach (<anonymous>)
      at Function.Object.<anonymous>.assert.file (node_modules/yeoman-assert/index.js:54:26)
      at Object.it (__tests__/app.js:13:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        28.139s
Ran all test suites.
npm ERR! Test failed.  See above for more details
```

Not sure how to fix that.
It might be that the bug is already fixed in the latest Jest version.

Updated to the more recent Jest version with: `npm install --save-dev jest-cli@23.6.0`

After update, did re-run the `npm audit` again to find out if there are any known security issues with the used npm packages. `npm audit` "found 0 vulnerabilities in 41220 scanned packages."

After that, tried to run `npm link` again to see if it would work now.
It completed without any issues.

So it seems that the core issues were the outdated Jest version,
and lack of migration from `nsp check` to `npm audit`.

After fixing those problems, it is finally possible to install the generator.

After that, tried re-running the `npm test` to see if the test results would have changed.
Still the same as before, but at least the main issues are now fixed.

**Comment by Jason3S** [comment]
Thank you for the fix. I'll pull it in.

**Comment by d2s** [comment]
Originally noticed this after trying to get back to making a new dictionary for various different sets of words & topics. Partly got inspired by a [tweet of Sara Vieira](https://twitter.com/NikkitaFTW/status/1072120929155723265):
> “[…] a website to help newcomers and designers understand
> some of the fancy words we use in dev world […]”

Another reason is that I have been noticing the need for making it easier to expand custom dictionaries, as the default set of words & patterns are limited by the amount of contributions. Making it easier to contribute would increase the possibility for more varied sets of wordlists.

**Comment by Jason3S** [comment]
Thank you for contributing!

**Comment by Jason3S** [comment]
The core of this issue has been fixed.
